import { Oxanium } from "next/font/google";
import "./globals.css";

const oxanium = Oxanium({
  weight: ["400", "600", "700"],
  display: "swap",
  subsets: ["latin"],
  variable: "--font-oxanium",
});

export const metadata = {
  title: "Factions App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html className={oxanium.variable}>
      <body>{children}</body>
    </html>
  );
}
